const LINKEDIN_LOGIN_PAGE_URL = 'https://www.linkedin.com/login';
const LOGIN_EMAIL_FIELD_SELECTOR = '#username';
const LOGIN_PASS_FIELD_SELECTOR = '#password';
const LOGIN_SUBMIT_BUTTON_SELECTOR =
  "button[data-litms-control-urn='login-submit']";
const LOGIN_SUBMIT_BUTTON_CLICK_TIMEOUT = 1500;
const LOGIN_SUBMIT_WAITING_TIME = 1000;

export {
  LINKEDIN_LOGIN_PAGE_URL,
  LOGIN_EMAIL_FIELD_SELECTOR,
  LOGIN_PASS_FIELD_SELECTOR,
  LOGIN_SUBMIT_BUTTON_SELECTOR,
  LOGIN_SUBMIT_BUTTON_CLICK_TIMEOUT,
  LOGIN_SUBMIT_WAITING_TIME,
};
